name: validate

on:
  push:
  pull_request:

env:
  LOG_LEVEL: debug

jobs:
  preset:
      runs-on: ubuntu-latest
      timeout-minutes: 10

      strategy:
        matrix:
          file:
            - default
            - dotnet
            - github-actions
            - npm
            - terraform

      env:
        RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

      steps:
        - name: Checkout
          uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

        - name: Validating ${{ matrix.file }}
          run: npx -p renovate renovate-config-validator
