name: validate

on:
  push:
  pull_request:

env:
  LOG_LEVEL: debug

jobs:
  preset:
      runs-on: ubuntu-latest
      timeout-minutes: 10

      strategy:
        matrix:
          file:
            - default
            - dotnet
            - github-actions
            - npm
            - terraform

      env:
        RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

      steps:
        - name: Checkout
          uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

        - name: Validating ${{ matrix.file }}
          run: npx -p renovate renovate-config-validator
