name: validate

on:
  push:
  pull_request:

env:
  LOG_LEVEL: debug

jobs:
  preset:
      runs-on: ubuntu-latest
      timeout-minutes: 10

      strategy:
        matrix:
          file:
            - default
            - dotnet
            - github-actions
            - npm
            - terraform

      env:
        RENOVATE_CONFIG_FILE: ${{ matrix.file }}.json

      steps:
        - name: Checkout
          uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

        - name: Validating ${{ matrix.file }}
          run: npx -p renovate renovate-config-validator
